# =============================================================
#  AnuRaj Jewellery - Gallery Updater
#  Scans the "products" folder and rebuilds data/products.js
#  so the website automatically shows your latest images.
#  (Run this by double-clicking Update-Gallery.bat)
# =============================================================

$ErrorActionPreference = "Stop"
$base = Split-Path -Parent $MyInvocation.MyCommand.Definition
Set-Location $base

# Display names for the known category folders.
$categoryNames = [ordered]@{
    "handmade-gifts"      = "Handmade Gifts"
    "gift-boxes"          = "Gift Boxes"
    "memory-boxes"        = "Memory Boxes"
    "photo-frames"        = "Photo Frames"
    "memory-books"        = "Memory Books"
    "handmade-jewellery"  = "Handmade Jewellery"
    "bangles"             = "Bangles"
    "hair-pins"           = "Hair Pins"
    "other-craft"         = "Other Handmade Crafts"
}

$imageExt = @(".jpg", ".jpeg", ".png", ".gif", ".webp", ".avif", ".bmp")

function Prettify($slug) {
    ($slug -split "[-_]" | ForEach-Object {
        if ($_.Length -gt 0) { $_.Substring(0,1).ToUpper() + $_.Substring(1) } else { $_ }
    }) -join " "
}

# Read optional info.txt (name:, price:, description:)
function Read-Info($folder) {
    $info = @{ name = $null; price = ""; description = "" }
    $file = Join-Path $folder "info.txt"
    if (Test-Path $file) {
        foreach ($line in Get-Content $file -Encoding UTF8) {
            if ($line -match "^\s*(name|price|description)\s*:\s*(.*)$") {
                $info[$matches[1].ToLower()] = $matches[2].Trim()
            }
        }
    }
    return $info
}

function Json-Escape($s) {
    if ($null -eq $s) { return "" }
    $s = $s -replace "\\", "\\\\"
    $s = $s -replace '"', '\"'
    $s = $s -replace "`r", ""
    $s = $s -replace "`n", "\n"
    $s = $s -replace "`t", "\t"
    return $s
}

$productsFolder = Join-Path $base "products"
if (-not (Test-Path $productsFolder)) {
    New-Item -ItemType Directory -Force -Path $productsFolder | Out-Null
}

$categoriesOut = @()
$productsOut = @()
$totalProducts = 0
$totalImages = 0

# Walk each category folder.
$categoryDirs = Get-ChildItem $productsFolder -Directory | Sort-Object Name
foreach ($catDir in $categoryDirs) {
    $catSlug = $catDir.Name
    if ($categoryNames.Contains($catSlug)) { $catName = $categoryNames[$catSlug] }
    else { $catName = Prettify $catSlug }

    $catProductCount = 0
    $catCover = ""

    # Each sub-folder is one product.
    $productDirs = Get-ChildItem $catDir.FullName -Directory | Sort-Object Name
    foreach ($prodDir in $productDirs) {
        $prodSlug = $prodDir.Name

        # Collect images in this product folder.
        $images = Get-ChildItem $prodDir.FullName -File |
            Where-Object { $imageExt -contains $_.Extension.ToLower() } |
            Sort-Object Name

        if ($images.Count -eq 0) { continue }

        # Choose the main image: a file named main.* wins, else first alphabetically.
        $mainImg = $images | Where-Object { $_.BaseName.ToLower() -eq "main" } | Select-Object -First 1
        if (-not $mainImg) { $mainImg = $images[0] }

        # Ordered image list: main first, then the rest.
        $ordered = @($mainImg) + ($images | Where-Object { $_.FullName -ne $mainImg.FullName })

        $relPaths = $ordered | ForEach-Object {
            ("products/$catSlug/$prodSlug/" + $_.Name) -replace "\\", "/"
        }

        $info = Read-Info $prodDir.FullName
        $name = if ($info.name) { $info.name } else { Prettify $prodSlug }
        $desc = if ($info.description) { $info.description } else { "Beautifully handcrafted $catName item from AnuRaj Jewellery." }
        $price = $info.price

        $id = "$catSlug`_`_$prodSlug"

        $imgJson = ($relPaths | ForEach-Object { '"' + (Json-Escape $_) + '"' }) -join ","

        $productsOut += @"
  {
    "id": "$(Json-Escape $id)",
    "name": "$(Json-Escape $name)",
    "category": "$(Json-Escape $catSlug)",
    "categoryName": "$(Json-Escape $catName)",
    "description": "$(Json-Escape $desc)",
    "price": "$(Json-Escape $price)",
    "thumb": "$(Json-Escape $relPaths[0])",
    "images": [$imgJson]
  }
"@

        if (-not $catCover) { $catCover = $relPaths[0] }
        $catProductCount++
        $totalProducts++
        $totalImages += $relPaths.Count
    }

    $categoriesOut += @"
  {
    "slug": "$(Json-Escape $catSlug)",
    "name": "$(Json-Escape $catName)",
    "cover": "$(Json-Escape $catCover)",
    "count": $catProductCount
  }
"@
}

$catBlock = $categoriesOut -join ",`n"
$prodBlock = $productsOut -join ",`n"
$stamp = (Get-Date).ToString("yyyy-MM-dd HH:mm")

$out = @"
/* ============================================================
   AnuRaj Jewellery - gallery data
   AUTO-GENERATED by update-gallery.ps1 on $stamp
   Do NOT edit by hand. To change products, edit the
   "products" folders and double-click Update-Gallery.bat
   ============================================================ */
window.ANURAJ_DATA = {
  "generated": "$stamp",
  "categories": [
$catBlock
  ],
  "products": [
$prodBlock
  ]
};
"@

$dataFolder = Join-Path $base "data"
if (-not (Test-Path $dataFolder)) { New-Item -ItemType Directory -Force -Path $dataFolder | Out-Null }
$out | Out-File -FilePath (Join-Path $dataFolder "products.js") -Encoding utf8

Write-Host ""
Write-Host "  AnuRaj Jewellery gallery updated successfully!" -ForegroundColor Green
Write-Host "  Categories               : $($categoriesOut.Count)"
Write-Host "  Products found           : $totalProducts"
Write-Host "  Images linked            : $totalImages"
Write-Host ""
Write-Host "  Open index.html in your browser to see the changes."
Write-Host ""
